services:
  - type: web
    name: tailoring-website
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn tailoring_website.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
    postDeployCommand: |
      python manage.py loaddata data.json || echo "Fixture already loaded"
