# Generated by Django 5.2.6 on 2025-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_measurement_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='bust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='gender',
            field=models.CharField(choices=[('male', "Men's"), ('female', "Women's")], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='shoulder',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
