# Generated by Django 5.2.6 on 2025-09-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_measurement_bust_measurement_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='gender',
            field=models.CharField(choices=[('male', "Men's"), ('female', "Women's")], default='male', max_length=10),
        ),
    ]
